### ISSUE TITLE
Audio quality on web and android

### ISSUE THREAD

**Issue by KONSTANTINOSKOUKOS** [diachedelic/capacitor-blob-writer#51]
I am using ytdl-core to retrieve an mp3 file as a blob and it seems that the audio quality of the file is fine when downloaded directly from the server. However, when I store a blob using this plugin (web w/fast mode and android, haven't tested iOS) I experience a drop in the quality of the file. I am writing and reading the file as shown in the README but I can't seem to find the reason of this. Thanks in advance.

**Comment by diachedelic** [comment]
That's very strange. There is no reason I can think of that this plugin would introduce a drop in quality, because it simply treats MP3s as binary data. It would have to be some kind of MP3 decoding issue. Because you are experiencing the problem both on the Android and Web platforms, that tells me it is something to do with Chrome. Please let me know if you find a way to fix the problem.
